### ISSUE TITLE
Check IRIS Compatibility (crash on egg hover)

### ISSUE THREAD

**Issue by Rooze93** [Okabintaro/UntitledDuckMod#31]
**Describe the bug**
My game crashes when i hover over one of the white eggs (i think its the goose spawn egg) with my RoughlyEnoughItems fabric mod AND in the creative search ui

[crash-2021-08-05_01.52.16-client.txt](https://github.com/Paspartout/UntitledDuckMod/files/6935006/crash-2021-08-05_01.52.16-client.txt)

**Version**
untitledduckmod-0.3.0-fabric
iris-mc1.17-1.1.1
RoughlyEnoughItems-6.0.264-alpha-fabric
fabric-api-0.36.0+1.17

**Comment by Okabintaro** [comment]
This is a duplicate of #40, since the crash is caused by inpecio.
