### ISSUE TITLE
Add Duck and geese Spwan Rate Configuration

### ISSUE THREAD

**Issue by Heamaci** [Okabintaro/UntitledDuckMod#38]
I don't think it makes sense how the duck and geese spawn in nearly every biome. Maybe a config option to restrict their spawn to lakes and rivers?

**Comment by Okabintaro** [comment]
Ducks and geese only spawn near rivers now since version v0.6.0.
The spawn rates can also be configured using a config file on fabric and biome modifiers on forge.
